### ISSUE TITLE
Wrap over-long collision labels.

### ISSUE THREAD

**Issue by Kashomon** [Kashomon/gpub#6]
Tricky to do in the general case, but collision labels should be wrapped when they grow too long.

Example: 
fujisawa vs go
(Moves: 189-205)
Black 95 at a, White 98 at 92, Black 1 at a, White 4 at 92.

**Comment by Kashomon** [comment]
Write now they're wrapped at 3 labels / line. This is ok since we're auto-replacing labels with move symbols.  I think the only way to really achieve this is to use the average char-width and wrap when the comment line is probably greater than the diagram. yuck.

**Comment by Kashomon** [comment]
closing for now. I think this is good enough for the time being.

**Comment by dormerod** [comment]
Could we revisit this please? Even with a relatively benign ko fight, the list can end up using a lot of vertical space. Have a look at this file for an example:

[02-20140223.pdf](https://github.com/Kashomon/gpub/files/8896/02-20140223.pdf)

**Comment by dormerod** [comment]
Now that most characters are being replaced with stones, the width seems much more predictable than before. Moreover, the (vertically) long collision lists are creating a lot of white space in games with kos (including in variations) and will waste paper.

Maybe a simple rule based on the character width of the board could work, because the board and the collision list mostly use the same characters (and the other characters are predictable and limited).

Can we please try something like (pseudo code):

```javascript
if horizontallyCropped(diagram) = TRUE {
  diagramWidth = halfWidth; // = 10
} else {
  diagramWidth = fullWidth; // = 20
}

listWidth = countSymbols(list) + 2;
if listWidth > diagramWidth {
  list = wrap(list, diagramWidth);
}

return list;
```

I'd prefer to resolve this issue now if you think this approach will work. It affects the layout of the whole book and uncertainty around this is blocking other work.

**Comment by Kashomon** [comment]
I already understood that this was a priority. In an case, I have no idea what you're shooting for in your pseudo code. I have some ideas about how to fix this.
